cache:
  - '%LOCALAPPDATA%\pip\cache -> requirements.txt'

install:
  - python -m pip install --upgrade virtualenv==15.0.2
  - python -m virtualenv venv
  - venv\scripts\pip install --upgrade "setuptools<45.0.0"
  - venv\scripts\activate
  - pip install -r requirements.txt

build_script:
  - '.\venv\Scripts\python setup.py bdist_wheel'

artifacts:
  - path: 'dist\*.whl'

test_script:
  - nosetests
