build: false

cache:
  - '%LOCALAPPDATA%\pip\cache -> requirements.txt'

install:
  - python -m pip install --upgrade virtualenv==15.0.2
  - python -m virtualenv venv
  - venv\scripts\activate
  - pip install -r requirements.txt

test_script:
  - nosetests
