#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup

kwargs = {'author': 'Adam Nagel',
          'author_email': 'adam.nagel@gmail.com',
          'classifiers': ['Intended Audience :: Science/Research',
                          'Topic :: Scientific/Engineering'],
          'description': 'OpenMDAO Wrapper for FMU',
          'download_url': '',
          'entry_points': '[openmdao.component]\nfmu_wrapper.FmuWrapper=fmu_wrapper:FmuWrapper\n\n[openmdao.container]\nfmu_wrapper.FmuWrapper=fmu_wrapper:FmuWrapper',
          'include_package_data': True,
          'install_requires': ['openmdao'],
          'keywords': ['openmdao, fmu'],
          'license': 'GNU General Public License, version 2',
          'maintainer': 'Adam Nagel',
          'maintainer_email': 'adam.nagel@gmail.com',
          'name': 'fmu_wrapper',
          'package_data': {'fmu_wrapper': ['fmu_wrapper.py',
                                           '__init__.py',
                                           'test/__init__.py',
                                           'test/test_fmu_wrapper.py',
                                           'test/bouncingBall.fmu']},
          'package_dir': {'': 'src'},
          'packages': ['fmu_wrapper', 'fmu_wrapper.test'],
          'url': '',
          'version': '0.1',
          'zip_safe': False}

setup(**kwargs)

